server:
  port: 9992
  servlet:
    context-path: /oauth

spring:
  application:
    name: oauth
  cloud:
    # nacos \u914D\u7F6E
    nacos:
      config:
        enabled: true
        server-addr: 10.0.0.152:8848
        file-extension: yaml
      discovery:
        enabled: true
        server-addr: 10.0.0.152:8848
        register-enabled: true

logging:
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
