server:
  port: 9993
  servlet:
    context-path: /met

spring:
  application:
    name: oauth
  influx:
    url: http://211.149.175.230:8086
    user: admin
    password: admin@Jydsoft@2022
    database: host_cpu

logging:
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
