server:
  port: 9999
  servlet:
    context-path: /learn-gateway

spring:
  application:
    name: learn-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    nacos:
      config:
        enabled: true
        server-addr: 10.0.0.167:8848
        file-extension: yaml
      discovery:
        enabled: true
        server-addr: 10.0.0.167:8848
        register-enabled: true

